(()=>{
const $=id=>document.getElementById(id);const state={mode:null,config:null,results:[],universe:null,metadata:null,running:false};
const KEY='codex-bq-key',WATCH='codex-watchlist',HISTORY='codex-scan-history',PROFILES='codex-scan-profiles';
const safe=()=>localStorage.getItem(KEY)||''; const saveJSON=(k,v)=>localStorage.setItem(k,JSON.stringify(v)); const loadJSON=(k,d=[])=>{try{return JSON.parse(localStorage.getItem(k)||'null')??d}catch{return d}};
function nav(name){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));document.querySelectorAll('[data-nav]').forEach(b=>b.classList.toggle('active',b.dataset.nav===name));$(`${name}View`).classList.add('active');if(name==='watchlist')renderWatchlist();if(name==='history')renderHistory();if(name==='settings')renderBudget();}
document.querySelectorAll('[data-nav]').forEach(b=>b.addEventListener('click',()=>nav(b.dataset.nav)));
function renderBudget(){const r=BQ_API.remaining(),u=BQ_API.usage();$('budgetChip').textContent=`API ${r}/${BQ_API.DAILY_LIMIT}`;$('budgetLarge').textContent=`${r} remaining today · ${u} used by Codex`;}
window.addEventListener('codex-api-usage',renderBudget);renderBudget();
function cfgBase(mode){return{mode,nyse:true,nasdaq:true,profitability:'positive',candidateLimit:50,minPrice:2,minMarketCap:100,maxPE:'',minROE:'',fcf:'any',dividend:'any',minAvgVolume:100000,maxBeta:'',betaLookback:252,gapThreshold:3,gapMinAge:5,gapMaxAge:60,gapDistance:5,rsiMin:mode==='gap'?35:45,rsiMax:mode==='gap'?55:75,confirmations:1,earlySensitivity:'early',volumeMultiplier:1.5,requireMomentum:mode==='best'};}
const modeInfo={best:['Best Opportunities','Balanced quality, value, trend and momentum.'],gap:['Gap-Fill Reversal','Profitable stocks pulling back toward an open bullish gap with improving momentum.'],early:['Early Golden Cross','SMA50 approaching SMA200 before the cross, confirmed by RSI and MACD.'],custom:['Build My Scan','Your answers translate into a focused fundamental and technical scan.']};
function selectMode(mode){state.mode=mode;state.config=cfgBase(mode==='custom'?'best':mode);document.querySelectorAll('.mode-card').forEach(x=>x.classList.toggle('selected',x.dataset.mode===mode));renderQuiz(mode);}
document.querySelectorAll('.mode-card').forEach(b=>b.addEventListener('click',()=>selectMode(b.dataset.mode)));
function choice(label,val,onClick,multi=false){const b=document.createElement('button');b.className='choice';b.textContent=label;b.dataset.value=val;b.onclick=()=>{if(!multi)b.parentElement.querySelectorAll('.choice').forEach(x=>x.classList.remove('on'));b.classList.toggle('on');onClick(val,b.classList.contains('on'));updateSummary();};return b;}
function step(title,options,onClick,multi=false){const d=document.createElement('div');d.className='quiz-step';d.innerHTML=`<h3>${title}</h3>`;const c=document.createElement('div');c.className='choices';options.forEach(o=>c.appendChild(choice(o[0],o[1],onClick,multi)));d.appendChild(c);return d;}
function renderQuiz(mode){const p=$('quizPanel');p.classList.remove('hidden');p.innerHTML='';const c=state.config;
 if(mode==='gap'){
  p.append(step('How close should price be to the open gap?',[['Within 2%','2'],['Within 5%','5'],['Within 10%','10'],['Already inside is okay','15']],v=>c.gapDistance=+v));
  p.append(step('How much confirmation do you want?',[['At least 1 signal','1'],['At least 2','2'],['Strong confluence (3)','3']],v=>c.confirmations=+v));
  p.append(step('How much RSI weakness can you tolerate?',[['35–55 recovery','35'],['30–60 wider','30'],['40–60 conservative','40']],v=>{if(v==='35'){c.rsiMin=35;c.rsiMax=55}else if(v==='30'){c.rsiMin=30;c.rsiMax=60}else{c.rsiMin=40;c.rsiMax=60}}));
 } else if(mode==='early'){
  p.append(step('How early should Codex look for the developing cross?',[['Very early','veryearly'],['Early','early'],['Near confirmation','near']],v=>c.earlySensitivity=v));
  p.append(step('How much momentum is too much?',[['Avoid overbought','65'],['Allow strong momentum','75'],['No practical ceiling','95']],v=>c.rsiMax=+v));
 } else {
  p.append(step('What matters most?',[['Quality','quality'],['Value','value'],['Momentum','momentum'],['Income','income']],(v,on)=>{c.focus=c.focus||[];c.focus=on?[...new Set([...c.focus,v])]:c.focus.filter(x=>x!==v);if(v==='income'&&on)c.dividend='yes';if(v==='quality'&&on)c.fcf='positive';if(v==='value'&&on)c.maxPE=25},true));
 }
 if(mode==='custom'){
  p.append(step('Risk tolerance',[['Conservative','conservative'],['Moderate','moderate'],['Aggressive','aggressive'],['Very aggressive','veryaggressive']],v=>{if(v==='conservative'){c.maxBeta=1;c.minMarketCap=1000}else if(v==='moderate'){c.maxBeta=1.5;c.minMarketCap=500}else if(v==='aggressive'){c.maxBeta=2;c.minMarketCap=100}else{c.maxBeta='';c.minMarketCap=50}}));
  p.append(step('Which company traits should be required?',[['Positive free cash flow','fcf'],['ROE ≥ 10%','roe'],['P/E ≤ 30','pe'],['Pays a dividend','div']],(v,on)=>{if(v==='fcf')c.fcf=on?'positive':'any';if(v==='roe')c.minROE=on?10:'';if(v==='pe')c.maxPE=on?30:'';if(v==='div')c.dividend=on?'yes':'any'},true));
 }
 p.append(step('How many companies should receive deep analysis?',[['25 · Minimal API','25'],['50 · Recommended','50'],['100 · Broader','100'],['250 · Deep scan','250']],v=>c.candidateLimit=+v));
 const go=document.createElement('button');go.className='btn primary';go.textContent='Review My Scan';go.onclick=updateSummary;p.appendChild(go);updateSummary();}
function mergeAdvanced(){const c=state.config;if(!c)return;c.minPrice=+$('minPrice').value||0;c.minMarketCap=+$('minMarketCap').value||0;c.maxPE=$('maxPE').value;c.minAvgVolume=+$('minAvgVolume').value||0;c.maxBeta=$('maxBeta').value;c.minROE=$('minROE').value;c.fcf=$('fcf').value;c.dividend=$('dividend').value;}
function estimateCalls(c){return 3+1+Math.ceil((+c.candidateLimit||50)/20);}
function updateSummary(){if(!state.config)return;mergeAdvanced();const c=state.config,s=$('scanSummary');s.classList.remove('hidden');const tags=['Positive net income',`${c.candidateLimit} deep candidates`];if(c.mode==='gap')tags.push(`Gap ≤ ${c.gapDistance}% away`,`RSI ${c.rsiMin}–${c.rsiMax}`,`${c.confirmations}+ confirmation`);if(c.mode==='early')tags.push(`Early cross: ${c.earlySensitivity}`,`RSI ≤ ${c.rsiMax}`);if(c.maxPE)tags.push(`P/E ≤ ${c.maxPE}`);if(c.fcf==='positive')tags.push('Positive FCF');if(c.minROE)tags.push(`ROE ≥ ${c.minROE}%`);s.innerHTML=`<div><h3>${modeInfo[state.mode][0]}</h3><div class="summary-tags">${tags.map(x=>`<span class="tag">${x}</span>`).join('')}</div><p class="muted">Estimated worst-case usage: about ${estimateCalls(c)} calls before cache savings.</p></div><div><button id="saveProfile" class="btn ghost">Save Profile</button> <button id="runScan" class="btn primary">Run Scan</button></div>`;$('runScan').onclick=runScan;$('saveProfile').onclick=saveProfile;}
function saveProfile(){const arr=loadJSON(PROFILES,[]);const name=prompt('Profile name:',`${modeInfo[state.mode][0]} Profile`);if(!name)return;arr.unshift({name,mode:state.mode,config:state.config,at:Date.now()});saveJSON(PROFILES,arr.slice(0,10));renderProfiles();alert('Profile saved on this device.');}
function renderProfiles(){const box=$('savedProfiles'),arr=loadJSON(PROFILES,[]);if(!arr.length){box.innerHTML='';return}box.innerHTML='<span class="muted" style="align-self:center">Saved:</span>'+arr.map((p,i)=>`<button class="profile-chip" data-profile="${i}">${p.name}</button>`).join('');box.querySelectorAll('[data-profile]').forEach(b=>b.onclick=()=>{const p=arr[+b.dataset.profile];state.mode=p.mode;state.config={...p.config};document.querySelectorAll('.mode-card').forEach(x=>x.classList.toggle('selected',x.dataset.mode===p.mode));renderQuiz(p.mode);state.config={...p.config};updateSummary();});}
renderProfiles();
function metricRows(meta){return Array.isArray(meta)?meta:(meta?.data||[])}
function pick(set,names){return names.find(n=>set.has(n))||null}
function buildFundQuery(c,meta){const set=new Set(metricRows(meta).map(x=>x.metric_full));const m={cap:pick(set,['Market Capitalization','Market Cap']),ni:pick(set,['Net Income (Yr)','Net Income (TTM)','Net Income']),pe:pick(set,['P/E Ratio','PE Ratio']),roe:pick(set,['Return on Equity (Yr)','Return on Equity','ROE (Yr)','ROE']),fcf:pick(set,['Free Cash Flow (TTM)','Free Cash Flow','FCF']),dy:pick(set,['Dividend Yield'])};if(!m.cap)throw new Error('Market Capitalization was not found in Business Quant screener metadata.');if(!m.ni)throw new Error('Net Income was not found in Business Quant screener metadata.');const cond=[`"${m.cap}" >= ${(+c.minMarketCap||0)*1e6}`,`"${m.ni}" > 0`],cols=Object.values(m).filter(Boolean);if(c.maxPE&&m.pe)cond.push(`"${m.pe}" <= ${+c.maxPE}`);if(c.minROE&&m.roe)cond.push(`"${m.roe}" >= ${+c.minROE}`);if(c.fcf==='positive'){if(!m.fcf)throw new Error('Free Cash Flow is not available in your screener metadata. Disable that optional filter or check your plan metadata.');cond.push(`"${m.fcf}" > 0`)}if(c.dividend==='yes'){if(!m.dy)throw new Error('Dividend Yield is not available in your screener metadata.');cond.push(`"${m.dy}" > 0`)}return{conditions:cond.join(' AND '),columns:[...new Set(cols)],m};}
function normPct(v){if(v==null||v==='')return null;return +(String(v).replace('%',''))}
function normFund(r,m,u){return{ticker:r.ticker,name:r.name_short||r.name||u.name_short||r.ticker,exchange:u.exchange||'',sector:r.sector||u.sector||'',industry:r.industry||u.industry||'',marketCap:m.cap?+r[m.cap]:null,netIncome:m.ni?+r[m.ni]:null,pe:m.pe?+r[m.pe]:null,roe:m.roe?normPct(r[m.roe]):null,freeCashFlow:m.fcf?+r[m.fcf]:null,dividendYield:m.dy?normPct(r[m.dy]):null};}
function parseQuotes(json,tickers){const out=new Map();for(const t of tickers){const b=json?.[t]||json?.data?.[t];if(Array.isArray(b?.data))out.set(t,b.data)}if(tickers.length===1&&Array.isArray(json?.data))out.set(tickers[0],json.data);return out;}
const iso=d=>d.toISOString().slice(0,10);
async function runScan(){if(state.running)return;if(!safe()){nav('settings');$('keyStatus').textContent='Add a Business Quant API key first.';return}mergeAdvanced();state.running=true;state.results=[];$('builder').classList.add('hidden');$('runArea').classList.remove('hidden');$('resultTitle').textContent=modeInfo[state.mode][0];setStatus('Preparing scan…',2);renderResults();try{const c=state.config,key=safe();const [uni,meta]=await Promise.all([BQ_API.universe(key),BQ_API.metadata(key)]);state.universe=uni;state.metadata=meta;const ur=uni?.data||uni||[];const allowed=ur.filter(x=>x.security_type==='Equity'&&['NYSE','NASDAQ'].includes(x.exchange));const um=new Map(allowed.map(x=>[x.ticker,x]));const q=buildFundQuery(c,meta);setStatus('Applying fundamental pre-screen…',8);const fr=await BQ_API.screener(key,q.conditions,q.columns,1,10000);let candidates=(fr?.data||[]).filter(x=>um.has(x.ticker)).map(x=>normFund(x,q.m,um.get(x.ticker))).sort((a,b)=>(b.marketCap||0)-(a.marketCap||0)).slice(0,+c.candidateLimit||50);if(!candidates.length){setStatus('No companies passed the fundamental pre-screen.',100);return}
 const days=520,from=iso(new Date(Date.now()-days*864e5)),till=iso(new Date());setStatus(`Fundamentals narrowed the market to ${candidates.length} candidates. Loading benchmark…`,12);const spy=parseQuotes(await BQ_API.quotes(key,['SPY'],from,till),['SPY']);const bench=MarketScanner.normalizeRows(spy.get('SPY')||[]);if(bench.length<60)throw new Error('SPY history could not be loaded for beta.');
 for(let i=0;i<candidates.length;i+=20){const batch=candidates.slice(i,i+20),ticks=batch.map(x=>x.ticker);setStatus(`Deep analysis ${Math.min(i+20,candidates.length)} / ${candidates.length}…`,12+78*(i/candidates.length));let map;try{map=parseQuotes(await BQ_API.quotes(key,ticks,from,till),ticks)}catch(e){throw e}for(const f of batch){const item=MarketScanner.analyzeStock(f,map.get(f.ticker)||[],bench,c);if(!item)continue;if(item.tech.price<c.minPrice)continue;if(c.maxBeta!==''&&Number.isFinite(item.tech.beta)&&item.tech.beta>+c.maxBeta)continue;if(item.tech.avgVolume20<c.minAvgVolume)continue;item.evaluation=MarketScanner.evaluate(item,c);state.results.push(item)}renderResults();}
 state.results.sort((a,b)=>b.scores.composite-a.scores.composite);const matches=state.results.filter(x=>x.evaluation.match).length,near=state.results.filter(x=>x.evaluation.near).length;setStatus(`Complete · ${matches} matches · ${near} near matches · ${state.results.length} analyzed`,100);recordHistory(matches,near);renderResults();}catch(e){setStatus(e.message,100,true)}finally{state.running=false;renderBudget();}}
function setStatus(txt,pct,error=false){$('statusText').textContent=txt;$('statusText').style.color=error?'var(--danger)':'';$('progressBar').style.width=`${pct}%`;}
function groupResults(){const g=$('resultGroup').value;if(g==='match')return state.results.filter(x=>x.evaluation.match);if(g==='near')return state.results.filter(x=>x.evaluation.near);return state.results;}
function fmt(n,d=2){return Number.isFinite(n)?n.toLocaleString(undefined,{maximumFractionDigits:d}):'—'}function money(n){return Number.isFinite(n)?'$'+n.toLocaleString(undefined,{maximumFractionDigits:2}):'—'}function cap(n){if(!Number.isFinite(n))return'—';return n>=1e9?'$'+fmt(n/1e9,1)+'B':'$'+fmt(n/1e6,0)+'M'}
function renderResults(){const box=$('resultCards');if(!state.results.length){box.innerHTML='<div class="empty">Results will appear here as Codex analyzes candidates.</div>';return}const arr=groupResults();if(!arr.length){box.innerHTML='<div class="empty">No stocks are in this result group. Try Near Matches or adjust the strategy.</div>';return}box.innerHTML=arr.map(x=>`<div class="stock-card" data-ticker="${x.ticker}"><div><div class="ticker">${x.ticker}</div><div class="company">${x.name}</div></div><div><div class="score">${x.scores.composite}</div><small class="muted">CODEX</small></div><div class="metric"><small>Price</small><b>${money(x.tech.price)}</b></div><div class="metric"><small>RSI</small><b>${fmt(x.tech.rsi,1)} ${x.tech.rsiRising?'↑':'↓'}</b></div><div class="metric"><small>MACD</small><b>${x.tech.macdImproving?'Improving':x.tech.macdBull?'Bullish':'Weak'}</b></div><div>${x.evaluation.match?'<span class="pill good">MATCH</span>':'<span class="pill warn">NEAR</span>'}</div><button class="watch" data-watch="${x.ticker}">${isWatched(x.ticker)?'★':'☆'}</button></div>`).join('');box.querySelectorAll('.stock-card').forEach(c=>c.addEventListener('click',e=>{if(e.target.dataset.watch)return;openDetail(c.dataset.ticker)}));box.querySelectorAll('[data-watch]').forEach(b=>b.onclick=e=>{e.stopPropagation();toggleWatch(b.dataset.watch);renderResults()});updateWatchCount();}
$('resultGroup').onchange=renderResults;$('newScan').onclick=()=>{$('builder').classList.remove('hidden');$('runArea').classList.add('hidden')};
function optionalNames(t){return[['Early Golden Cross',t.earlyGolden],['MACD crossover',t.macdCross],['RSI bullish divergence',t.rsiDivergence],['Bollinger reversal',t.bollingerReversal],['Unusual volume',t.unusualVolume],['Higher low',t.higherLow],['Bullish engulfing',t.bullishEngulfing],['SMA20 reclaim',t.sma20Reclaim]].filter(x=>x[1]).map(x=>x[0]);}
function openDetail(ticker){const x=state.results.find(r=>r.ticker===ticker)||loadJSON(WATCH,[]).find(r=>r.ticker===ticker);if(!x)return;const t=x.tech,s=x.scores,g=t.gap;const why=x.evaluation?.reasons||[],$c=$('detailContent');$c.innerHTML=`<span class="kicker">${x.exchange} · ${x.sector||'Sector unavailable'}</span><h1>${x.ticker} · ${x.name}</h1><p class="muted">Codex ${s.composite}/100 · ${x.evaluation?.match?'Strategy match':'Research candidate'}</p><div class="score-grid">${Object.entries(s).filter(([k])=>k!=='composite').map(([k,v])=>`<div class="subscore"><span>${k[0].toUpperCase()+k.slice(1)}</span><b>${v}</b></div>`).join('')}</div><canvas id="priceChart" width="850" height="240"></canvas><div class="why"><b>Why this ${x.evaluation?.match?'matched':'is worth reviewing'}</b><div class="checks">${why.map(v=>`<span class="ok">✓ ${v}</span>`).join('')}${(x.evaluation?.miss||[]).map(v=>`<span class="bad">✕ ${v}</span>`).join('')}</div></div><div class="detail-grid"><div class="detail-box"><small>Price</small><h3>${money(t.price)}</h3></div><div class="detail-box"><small>RSI 14</small><h3>${fmt(t.rsi,1)} ${t.rsiRising?'↑':'↓'}</h3></div><div class="detail-box"><small>Beta</small><h3>${fmt(t.beta,2)}</h3></div><div class="detail-box"><small>Market cap</small><h3>${cap(x.marketCap)}</h3></div><div class="detail-box"><small>P/E</small><h3>${fmt(x.pe,1)}</h3></div><div class="detail-box"><small>ROE</small><h3>${fmt(x.roe,1)}%</h3></div></div>${g?`<h3>Gap-Fill Setup</h3><div class="detail-grid"><div class="detail-box"><small>Gap zone</small><h3>${money(g.bottom)} → ${money(g.top)}</h3></div><div class="detail-box"><small>Gap age</small><h3>${g.age} sessions</h3></div><div class="detail-box"><small>Current fill</small><h3>${fmt(g.fillPct,0)}%</h3></div><div class="detail-box"><small>Distance above gap</small><h3>${fmt(g.distanceAbovePct,1)}%</h3></div></div>`:''}<h3>Technical confirmations</h3><p>${optionalNames(t).length?optionalNames(t).map(v=>`<span class="tag">${v}</span>`).join(' '):'No optional confirmations detected.'}</p>`;$('detailDialog').showModal();requestAnimationFrame(()=>drawChart(t));}
function drawChart(t){const c=$('priceChart');if(!c)return;const ctx=c.getContext('2d'),rows=t.rows.slice(-120);ctx.clearRect(0,0,c.width,c.height);if(rows.length<2)return;const vals=rows.flatMap(r=>[r.high,r.low]),min=Math.min(...vals),max=Math.max(...vals),x=i=>20+i*(c.width-40)/(rows.length-1),y=v=>20+(max-v)*(c.height-40)/(max-min||1);if(t.gap){ctx.fillStyle='rgba(193,123,61,.16)';ctx.fillRect(20,y(t.gap.top),c.width-40,y(t.gap.bottom)-y(t.gap.top));}ctx.strokeStyle='#e0a568';ctx.lineWidth=2;ctx.beginPath();rows.forEach((r,i)=>i?ctx.lineTo(x(i),y(r.close)):ctx.moveTo(x(i),y(r.close)));ctx.stroke();const line=(p,col)=>{ctx.strokeStyle=col;ctx.lineWidth=1;ctx.beginPath();let started=false;rows.forEach((r,j)=>{const gi=t.rows.length-rows.length+j;if(gi<p-1)return;const a=t.rows.slice(gi-p+1,gi+1).map(z=>z.close),v=a.reduce((s,z)=>s+z,0)/p;if(!started){ctx.moveTo(x(j),y(v));started=true}else ctx.lineTo(x(j),y(v))});ctx.stroke()};line(20,'#7fc49a');line(50,'#91aee7');line(200,'#d78585');}
$('closeDetail').onclick=()=>$('detailDialog').close();
function isWatched(t){return loadJSON(WATCH,[]).some(x=>x.ticker===t)}function toggleWatch(t){let a=loadJSON(WATCH,[]);const i=a.findIndex(x=>x.ticker===t);if(i>=0)a.splice(i,1);else{const r=state.results.find(x=>x.ticker===t);if(r)a.unshift({...r,tech:{...r.tech,rows:r.tech.rows.slice(-260)},savedAt:Date.now()})}saveJSON(WATCH,a);updateWatchCount();}function updateWatchCount(){$('watchCount').textContent=loadJSON(WATCH,[]).length}updateWatchCount();
function renderWatchlist(){const a=loadJSON(WATCH,[]),b=$('watchlistCards');if(!a.length){b.innerHTML='<div class="empty">Your watchlist is empty. Star a scan result to save it.</div>';return}b.innerHTML=a.map(x=>`<div class="stock-card" data-ticker="${x.ticker}"><div><div class="ticker">${x.ticker}</div><div class="company">${x.name}</div></div><div class="score">${x.scores?.composite||'—'}</div><div class="metric"><small>Price at save</small><b>${money(x.tech?.price)}</b></div><div class="metric"><small>RSI</small><b>${fmt(x.tech?.rsi,1)}</b></div><div class="metric"><small>Saved</small><b>${new Date(x.savedAt).toLocaleDateString()}</b></div><span class="pill good">WATCHING</span><button class="watch" data-remove="${x.ticker}">★</button></div>`).join('');b.querySelectorAll('.stock-card').forEach(c=>c.onclick=e=>{if(e.target.dataset.remove)return;openDetail(c.dataset.ticker)});b.querySelectorAll('[data-remove]').forEach(x=>x.onclick=e=>{e.stopPropagation();toggleWatch(x.dataset.remove);renderWatchlist()});}
function recordHistory(matches,near){const a=loadJSON(HISTORY,[]);a.unshift({at:Date.now(),mode:state.mode,title:modeInfo[state.mode][0],matches,near,candidates:state.config.candidateLimit,callsUsed:BQ_API.usage()});saveJSON(HISTORY,a.slice(0,20));}
function renderHistory(){const a=loadJSON(HISTORY,[]),b=$('historyList');b.innerHTML=a.length?a.map(x=>`<div class="history-item"><div><b>${x.title}</b><div class="muted">${new Date(x.at).toLocaleString()} · Deep analysis ${x.candidates}</div></div><div><b>${x.matches} matches</b><div class="muted">${x.near} near matches</div></div></div>`).join(''):'<div class="empty">No completed scans yet.</div>';}
$('exportBtn').onclick=()=>{const a=groupResults();if(!a.length)return;const headers=['Ticker','Company','Codex Score','Price','RSI','MACD','Beta','Market Cap','Net Income','P/E','ROE','Gap Bottom','Gap Top','Gap Fill %','Early Golden Cross','Match'];const rows=a.map(x=>[x.ticker,x.name,x.scores.composite,x.tech.price,x.tech.rsi,x.tech.macd,x.tech.beta,x.marketCap,x.netIncome,x.pe,x.roe,x.tech.gap?.bottom||'',x.tech.gap?.top||'',x.tech.gap?.fillPct||'',!!x.tech.earlyGolden,x.evaluation.match]);const csv=[headers,...rows].map(r=>r.map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(',')).join('\n');const blob=new Blob([csv],{type:'text/csv'}),u=URL.createObjectURL(blob),ael=document.createElement('a');ael.href=u;ael.download=`codex-${state.mode}-scan.csv`;ael.click();URL.revokeObjectURL(u)};
$('saveKey').onclick=async()=>{const k=$('apiKey').value.trim();if(!k)return;$('keyStatus').textContent='Testing…';try{await BQ_API.test(k);localStorage.setItem(KEY,k);$('keyStatus').textContent='Connection successful. API key saved only in this browser.';renderBudget()}catch(e){$('keyStatus').textContent=e.message}};$('apiKey').value=safe();$('clearCache').onclick=()=>{BQ_API.clearCache();$('keyStatus').textContent='Cached universe, metadata, and quote batches cleared.'};
['minPrice','minMarketCap','maxPE','minAvgVolume','maxBeta','minROE','fcf','dividend'].forEach(id=>$(id).addEventListener('change',()=>state.config&&updateSummary()));
})();
